spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/hotelappDB
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.sxrpcqaagmmiezrwkhxj
    password: Postgres123+

#Para tener dinámico el url del front, util para CORS
app:
  front:
    #url: ${FRONT_URL}
    url: http://localhost:4200